version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Build initiated by $CODEBUILD_INITIATOR
      - echo Starting deployment to ECS
      # ECS cluster and service must exist in AWS Elastic Container Service
      - ECS_CLUSTER=cognito-workshop-cluster
      - ECS_SERVICE_NAME=cognito-workshop-service
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_NAME --force-new-deployment
      - echo Finished deployment
