version: "3.7"
services:
  app:
    build:
      # This image is used for development running nodemon with your shared source files.
      context: ./
      dockerfile: ./etc/node/Dockerfile.dev
    image: express-ts-ddd
    container_name: express-ts-ddd
    restart: unless-stopped
    working_dir: /app/
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      APP_NAME: "express-ts-ddd"
      APP_ENV: "development"
      APP_LOG_LEVEL: "debug"
    networks:
      - express-ts-ddd-network

  nginx:
    build:
      context: ./
      dockerfile: ./etc/nginx/Dockerfile
    container_name: express-ts-ddd-nginx
    environment:
      PORT: 8080
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - express-ts-ddd-network
    depends_on:
      - app

networks:
  express-ts-ddd-network:
    driver: bridge
