version: "3.7"
services:
  app:
    build:
      # This image is used for development running nodemon with your shared source files.
      context: ./
      dockerfile: ./etc/node/Dockerfile.dev
    image: cognito-workshop
    container_name: cognito-workshop-app
    restart: unless-stopped
    working_dir: /app/
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      APP_NAME: "cognito-workshop"
    networks:
      - cognito-workshop-network

  nginx:
    build:
      context: ./
      dockerfile: ./etc/nginx/Dockerfile
    container_name: cognito-workshop-nginx
    environment:
      PORT: 8080
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - cognito-workshop-network
    depends_on:
      - app

networks:
  cognito-workshop-network:
    driver: bridge
